on:
  push:
    branches: ["main"]
  workflow_dispatch: 

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  codeql-security-analysis:
    name: Security Analysis
    uses: ./.github/workflows/codeql-security-analysis.yaml
    secrets: inherit
    permissions:
      security-events: write
      packages: read

  docker:
    needs: codeql-security-analysis
    name: Docker
    uses: ./.github/workflows/docker.yaml
    secrets: inherit

  notify_team:
    needs: docker
    uses: ./.github/workflows/notify.yaml
    secrets: inherit
