on:
  push:
    workflow_dispatch:
    branches: ["main"]
    tags: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml

  codeql-security-analysis:
    name: Security Analysis
    uses: ./.github/workflows/codeql-security-analysis.yaml
    secrets: inherit
    permissions:
      security-events: write
      packages: read

  docker:
    needs: codeql-security-analysis
    name: Docker
    uses: ./.github/workflows/docker.yaml
    secrets: inherit